/**
 * Copyright (C) 2014 The Motel on Jupiter
 */
#ifndef MOJGAMELIB_INCLUDER_SDLIMAGEINCLUDE_H_
#define MOJGAMELIB_INCLUDER_SDLIMAGEINCLUDE_H_

#ifdef MOJGAMELIB_WITH_SDLIMAGE

#include <SDL_image.h>

#endif /* MOJGAMELIB_WITH_SDLIMAGE */

#endif /* MOJGAMELIB_INCLUDER_SDLIMAGEINCLUDE_H_ */
