/**
 * Copyright (C) 2014 The Motel on Jupiter
 */
#ifndef MOJGAMELIB_INCLUDER_SDLTTFINCLUDE_H_
#define MOJGAMELIB_INCLUDER_SDLTTFINCLUDE_H_

#ifdef MOJGAMELIB_WITH_SDLTTF

#include <SDL_ttf.h>

#endif /* MOJGAMELIB_WITH_SDLTTF */

#endif /* MOJGAMELIB_INCLUDER_SDLTTFINCLUDE_H_ */
